enum UserTypes {
    USER_ACTION_START = "USER_ACTION_START",
    USER_ACTION_END = "USER_ACTION_END",
    USER_ACTION_SUCCESS = "USER_ACTION_SUCCESS",
    USER_ACTION_FAILED = "USER_ACTION_FAILED",
}

export default UserTypes 